spring:
  threads:
    virtual:
      enabled: true
  application:
    name: service-account
    version: '@project.version@'
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss:SSS z} [%t] %-5level %logger - %m%n'
