spring:
  application:
    name: service-payment
    version: '@project.version@'
  config:
    import: optional:configserver:http://localhost:8888
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss:SSS z} [%t] %-5level %logger - %m%n'
